### ISSUE TITLE
Speaker for Chill Room?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/remote-working#2]
https://www.worten.pt/inicio/campanhas/mega-24/colunas-e-docks-m24/coluna-bluetooth-lg-np1540w-branco.html

**Comment by nelsonic** [comment]
![worten-magento-fail](https://cloud.githubusercontent.com/assets/194400/8252336/e3bd30fa-167c-11e5-9c57-57f7882c41c0.png)

Don't you just love Magento? :wink:

**Comment by iteles** [comment]
What you linked to no longer appears but yes, I was just thinking about this last night.
Apparently Worten has a sale on til Sunday.
